<a href="https://colab.research.google.com/github/Enoch-Oluwanifemi/Consumer-Analytics/blob/JSON-review/My_JSON_reviews_to_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json
import pandas as pd

In [ ]:
file_path = '/content/data.json'
with open(file_path, 'r') as file:
    data = json.load(file)

In [ ]:
reviews_data = []
count = 0
for result in data['results']:
  asin = result['content']["asin"]
  for review in result['content']['reviews']:
    count += 1
    try:
      review_info = {
      'review_id': review['id'],
      'product_id': asin,
      "title": review["title"],
      "author": review["author"],
      "rating": review["rating"],
      "content": review["content"],
      "timestamp": review["timestamp"],
      "profile_id": review["profile_id"],
      "is_verified": review["is_verified"],
      "helpful_count": review.get('helpful_count', 0),
      "product_attributes": review["product_attributes"]
      }
      reviews_data.append(review_info)
    except:
      print(count)
      break

reviews_df = pd.DataFrame(reviews_data)
reviews_df.to_csv('reviews.csv', index=False)
reviews_df

84
85

,review_id,product_id,title,author,rating,content,timestamp,profile_id,is_verified,helpful_count,product_attributes
0,R2SSSH04J4J264,B0D4SX9RC6,5.0 out of 5 stars Really nice portable speake...,Bruce C,5,Needed a new portable speaker for the home set...,"Reviewed in the United States July 1, 2024",AFVM53KRAU5JC462ZZDBBKTESPGA,True,18,Color: Statement RedStyle: PillPattern: Withou...
1,R4BQHA0TLLJNN,B0D4SX9RC6,5.0 out of 5 stars The best Speaker I have eve...,Leox,5,I really like the new Beats Pill 2024 speaker....,"Reviewed in the United States July 11, 2024",AEUCX7EIPTMCFN4OJBZHL2OYSVKQ,True,8,Color: Champagne GoldStyle: PillPattern: Witho...
2,R39X7USU3OX34C,B0D4SX9RC6,5.0 out of 5 stars Really good,Justin,5,So I’m super picky about sound and have spent ...,"Reviewed in the United States July 8, 2024",AFSZPNTTLYCLNP536L6VS6UMFTNQ,True,7,Color: Statement RedStyle: PillPattern: Withou...
3,R1BHCCLK5GZ5VZ,B0D4SX9RC6,5.0 out of 5 stars Beats Pill,Gregory Stratman,5,"I love the size, weight and quality of my Pill...","Reviewed in the United States August 2, 2024",AHCXUEC2FLLJ3S6F762OSBZJRDPA,True,5,Color: Matte BlackStyle: PillPattern: Without ...
4,R2EVRTXO9M1YF7,B0D4SX9RC6,4.0 out of 5 stars Is it the JBL killer?,Tommy,4,"I bought this because it was on sale, and I al...","Reviewed in the United States July 23, 2024",AHAMVBSECCNUJMQV6A3BO3A3HNMA,True,5,Color: Matte BlackStyle: PillPattern: Without ...
...,...,...,...,...,...,...,...,...,...,...,...
78,R2H42JDX6Y37E,B0D4SX9RC6,5.0 out of 5 stars Best beats pill ever !,B,5,If you’re in need of a new lightweight portabl...,"Reviewed in the United States June 30, 2024",AFNLS7O6IJVQTC4QVORI4QIHSAEA,False,1,Color: Statement RedStyle: PillPattern: Withou...
79,R3L2A88GOC5G6I,B0D4SX9RC6,5.0 out of 5 stars Good speaker,Oli Rivers,5,The media could not be loaded. For a smallish ...,"Reviewed in the United States July 1, 2024",AFZK22BJRF7EXCXKGIVXNXI2BPPA,False,5,Color: Matte BlackStyle: PillPattern: Without ...
80,R99X2DXJ9IWPM,B0D4SX9RC6,5.0 out of 5 stars Rlly good,Luis dejesus,5,The media could not be loaded. Great audio lou...,"Reviewed in the United States July 2, 2024",AGANNLHAZNLD5K6NVFMJX3X6HFEQ,False,5,Color: Statement RedStyle: PillPattern: Withou...
81,R2AZVHS8KVEN85,B0D4SX9RC6,1.0 out of 5 stars Switches off quickly and un...,Dr. Help,1,"Had great hopes for this speaker, but unfortun...","Reviewed in the United States July 31, 2024",AH2LWMGL3K3SJYIKYDMISWPBAIWQ,False,5,Color: Matte BlackStyle: PillPattern: Without ...
82,R1M5XRE8PLEVIL,B0D4SX9RC6,5.0 out of 5 stars Beats Pill,DCF,5,"I so glad I finally got one, I’ve been wanting...","Reviewed in the United States September 5, 2024",AHU4A2NTGBQFW24HDYQ5L4K6GUTQ,True,0,Color: Matte BlackStyle: PillPattern: Without ...

In [ ]:
len(reviews_df)

83

In [ ]:
df = pd.read_csv('/content/reviews.csv')
df_1 = pd.read_csv('/content/reviews_1.csv')
df_2 = pd.read_csv('/content/reviews_2.csv')
df_3 = pd.read_csv('/content/reviews_3.csv')
df_4 = pd.read_csv('/content/reviews_4.csv')
df_5 = pd.read_csv('/content/reviews_5.csv')
df_6 = pd.read_csv('/content/reviews_6.csv')
df_7 = pd.read_csv('/content/reviews_7.csv')
df_8 = pd.read_csv('/content/reviews_8.csv')
df_9 = pd.read_csv('/content/reviews_9.csv')


df_3.head()

,review_id,product_id,title,author,rating,content,timestamp,profile_id,is_verified,helpful_count,product_attributes
0,R22P9TAALZTP3X,B0B43Y8GHZ,5.0 out of 5 stars Awesome speaker.,Stephen M.,5,The sound of this speaker is incredible. Good ...,"Reviewed in the United States August 29, 2024",AF7LYPOQCT7STDHZITCSNE24VFIQ,True,1,Color: BlackStyle: SRSXG300/B
1,R1DAHK2RQS1SII,B0B43Y8GHZ,5.0 out of 5 stars This is the IT speaker,Noah,5,"Firstly, I must say that the sound quality is ...","Reviewed in the United States July 23, 2023",AEIKMFWY3SV4YRDCG2KL6OTUP4TQ,True,31,Color: Light GrayStyle: SRSXG300/H
2,R123BOARGUG1WM,B0B43Y8GHZ,5.0 out of 5 stars All around great speaker,A like minded person,5,I bought the bigger 500 series and thought to ...,"Reviewed in the United States August 20, 2024",AEIXT4EMUTOBCXAIK4QDHTA3VPYQ,True,2,Color: BlackStyle: SRSXG300/B
3,R2T2U63981MT2C,B0B43Y8GHZ,4.0 out of 5 stars Sounds Great When Dialed In,Mike Blumenberg,4,"Out of the box, this speaker sounds pretty med...","Reviewed in the United States March 20, 2024",AHHXAFJW5QRATN2RFEG5TFFQHOXQ,True,11,Color: BlackStyle: SRSXG300/B
4,R1NBOJS21O8D3K,B0B43Y8GHZ,5.0 out of 5 stars Absolutely incredible battery,Rodney Molidor,5,This Sony XG500 boombox sounds good and has ab...,"Reviewed in the United States July 23, 2024",AGCI7M4EX5GHPCKJUSXWLKXVMADA,True,6,Color: BlackStyle: SRSXG500

In [ ]:
merged_df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9], ignore_index=True)
merged_df

,review_id,product_id,title,author,rating,content,timestamp,profile_id,is_verified,helpful_count,product_attributes
0,R3AK5LLZ1VVTWJ,B08X4YMTPM,"5.0 out of 5 stars INSANE Speaker! Quality, vo...",Jeremy,5,The JBL Charge 5 is the BEST speaker I have ev...,"Reviewed in the United States April 5, 2024",AEDM32EKQE2HOHUCSXFF2Z27F7NQ,True,78,Color: Black
1,R158T5SJCSV7IQ,B08X4YMTPM,5.0 out of 5 stars Amazing Sound and Great Dur...,Miguel Gomez,5,The media could not be loaded. I recently got ...,"Reviewed in the United States May 30, 2024",AEPFUMZ5YUTQEWFAW7FOQKK4BDBA,True,27,Color: Black
2,RPPZYO5WBVQNH,B08X4YMTPM,5.0 out of 5 stars Great portable speaker with...,Plumb,5,I use this as a bathroom/shower music speaker....,"Reviewed in the United States August 14, 2024",AEACBN7FOBQLIKTLCWVKIZIVX5XA,True,3,Color: Gray
3,R3VELE8MJDOXTB,B08X4YMTPM,"5.0 out of 5 stars So far, absolutely amazing.",TO Scar,5,I owned several different brands and sizes of ...,"Reviewed in the United States August 10, 2024",AEKSQ4KY6YUN5KM6XRQLMYRK23OA,True,1,Color: Camouflage
4,R2QS5H43BWOA9G,B08X4YMTPM,5.0 out of 5 stars Size/Sound/Play Time,Joseph Espinoza,5,"Had a decent balance of SIZE, SOUND, and BATTE...","Reviewed in the United States September 1, 2024",AFJ3IAEJ2XI4YCHHVUIEA2YKVMUQ,True,0,Color: Blue
...,...,...,...,...,...,...,...,...,...,...,...
815,RGLNYEW0F5G4D,B078HG6WNX,1.0 out of 5 stars Don’t wait your money,Katey,1,Item was super scratched up and missing charge...,"Reviewed in the United States October 20, 2020",AFNSSNCSW35CKXXN3OTTG5JWTODQ,True,1,Color: Black
816,RLNNX9EBRLYZ9,B078HG6WNX,1.0 out of 5 stars Why buy this new one is out,Josian Lopez,1,Why would you buy this when the new one is out...,"Reviewed in the United States July 23, 2024",AFDDWTYM3XZZLMIRF2GSBUX2OTHQ,False,0,Color: Black
817,R2S1GDO4SA9OXP,B078HG6WNX,5.0 out of 5 stars Ese speaker es uno de Los m...,Anthony Quinde,5,Es el mejor speaker que he probado solo que ya...,"Reviewed in the United States November 21, 2023",AHOJPOBBQK7MVCBJDH6S25K35F5Q,False,0,Color: White
818,R3BYDP94WUXU48,B078HG6WNX,1.0 out of 5 stars Never even turned on. Defec...,Buyera,1,Didn’t work upon opening,"Reviewed in the United States December 4, 2019",AGZ7YZ6QHD6ZDKCDYTBCOHSJKZEA,True,1,Color: Black
819,RUZ22XWO59V5S,B078HG6WNX,5.0 out of 5 stars SUPER LIT ONM,Jaelyn G.,5,Was a little nervous about the “renewed” in th...,"Reviewed in the United States December 10, 2019",AGZNXPKXJ3EGCN24ZFG5334FBOUQ,False,0,Color: Black

In [ ]:
merged_df.to_csv('merged_data.csv', index=False)